# Generated by Django 3.2.8 on 2021-12-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseManagement', '0003_auto_20211216_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(to='CourseManagement.Category', verbose_name='category of course'),
        ),
    ]
