# Generated by Django 3.2.8 on 2021-12-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseManagement', '0004_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='CourseDefault.jpg', null=True, upload_to='Course/%Y/%m/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='Course/%Y/%m/', verbose_name='2nd Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Course/%Y/%m/', verbose_name='3rd Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Course/%Y/%m/', verbose_name='4th Image'),
        ),
    ]
