# Generated by Django 3.2.8 on 2022-01-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseManagement', '0007_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(blank=True, to='CourseManagement.Category', verbose_name='category of course'),
        ),
    ]
