# Generated by Django 3.2.8 on 2021-12-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='refrence_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
