# Generated by Django 3.2.8 on 2021-12-17 13:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_auto_20211217_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='df_Avatar.jpg', null=True, upload_to='UserAvatar/%Y/%m/%d/', verbose_name='Profile Avatar')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(15.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
