# Generated by Django 3.2.8 on 2021-12-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='UserAvatar/df_Avatar.jpg', null=True, upload_to='UserAvatar/%Y/%m/%d/', verbose_name='Profile Avatar'),
        ),
    ]
